name: envs
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
          - test
jobs:
  deployment:
    strategy:
      matrix:
        secret: ${{ fromJSON(secrets) }}
        #secret: [ "BLARGH", "KRRR" ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    steps:
      - name: deploy
        run: |
          echo "${{ matrix.secret }}: ${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
