name: envs
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
          - e
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    steps:
      - name: deploy
        run: |
          echo BLARGH
          echo ${{ secrets.BLARGH }} | tr '[:lower:]' '[:upper:]'
