name: envs
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
          - test
env:
  CLUSTER: ${{ fromJson('{ "dev": "dev_cluster", "test": "test_cluster" }')[github.event.inputs.namespace] }}

jobs:
  deployment:
    strategy:
      matrix:
        secret: [ "BLARGH", "KRRR" ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    steps:
      - name: deploy
        run: |
          echo env.CLUSTER
          echo "${{ matrix.secret }}: ${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
          echo "${{ matrix.secret }}: ${{ inputs.namespace }}_${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
