name: envs
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: |
          echo blargh
          echo ${{ secrets.BLARGH }}
          echo ${{ secrets }}
