name: envs
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - e
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: e
    steps:
      - name: deploy
        run: |
          echo wurst
          echo ${{ secrets.THE_ONE }}
