name: envs
run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
          - e
jobs:
  deployment:
    strategy:
      matrix:
        secrets: [ "BLARGH", "KRRR" ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    steps:
      - name: deploy
        run: |
          echo "${{ matrix.secrets }}: ${{ secrets[matrix.secrets] }}" | tr '[:lower:]' '[:upper:]'
