name: envs
#run-name: ${{ github.actor }}
run-name: wurst
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
          - test
env:
  GCP_PROJECT: >
    ${{ fromJson(
          '{
            "dev":"dev_cluster",
            "test":"test_cluster"
           }'
        )[inputs.namespace] }}

jobs:
  deployment:
    strategy:
      matrix:
        secret: [ "BLARGH", "KRRR" ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    steps:
      - name: deploy
        run: |
          echo ${{ env.GCP_PROJECT }}
          echo "${{ matrix.secret }}: ${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
          echo "${{ matrix.secret }}: ${{ inputs.namespace }}_${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
