name: Transfere github env to secret manager
#run-name: ${{ github.actor }}
run-name: "Env: ${{ inputs.namespace }}"
on: 
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        options:
          - dev
          - test
env:
  GCP_PROJECT: >
    ${{ fromJson(
          '{
            "dev":"dev_cluster",
            "test":"test_cluster"
           }'
        )[inputs.namespace] }}

jobs:
  secret:
    name: Set Secrets in Secret Manager
    strategy:
      matrix:
        secret: [ "BLARGH", "KRRR", "ONK" ]
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    steps:
      - name: Print for debugging
        run: |
          if [ "${{ secrets[matrix.secret] }}" = "" ]; then
            echo "${{ matrix.secret }} is empty"
            exit 1
          fi
          echo ${{ env.GCP_PROJECT }}
          echo "${{ matrix.secret }}: ${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
          echo "${{ matrix.secret }}: ${{ inputs.namespace }}_${{ secrets[matrix.secret] }}" | tr '[:lower:]' '[:upper:]'
